apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kf-release-users.fullname" . }}
  namespace: nginx-ingress  # Thêm namespace để khớp với cấu hình gốc
  labels:
    app: kf-users
    {{- include "kf-release-users.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}  # Số lượng replicas có thể cấu hình
  {{- end }}
  selector:
    matchLabels:
      app: kf-users
      {{- include "kf-release-users.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kf-users  # Đặt nhãn app cho các Pods
        {{- include "kf-release-users.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000  # Khớp với cấu hình cổng gốc
          command: ["/home/node/app/start.sh"]  # Lệnh start.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /v1/users
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/users
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/hostname: k8s-development-master