apiVersion: v1
kind: Service
metadata:
  name: {{ include "kf-release-users.fullname" . }}
  labels:
    {{- include "kf-release-users.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30888
  selector:
    {{- include "kf-release-users.selectorLabels" . | nindent 4 }}