apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-deployment-roles
  namespace: nginx-ingress
  labels:
    app: kf-roles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kf-roles
  template:
    metadata:
      labels:
        app: kf-roles
    spec:
      containers:
        - name: kf-roles
          image: harbor.minhnguyen.info.vn/kfm-devops/kf_stack_kf_roles:development-13864683
          ports:
            - containerPort: 3000
          command: ["/home/node/app/start.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: kf-service-roles
  namespace: nginx-ingress
spec:
  type: NodePort
  selector:
    app: kf-roles
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30888